# Generated by Django 5.1.7 on 2025-03-06 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_customuser_nickname_alter_notification_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="nickname",
        ),
    ]
