# Generated by Django 5.1.6 on 2025-03-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_remove_customuser_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
